
[cursor]
style = "Block"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = true

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
