add_newline = false
command_timeout = 1000
scan_timeout = 30

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[line_break]
disabled = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[cmd_duration]
min_time = 100
show_milliseconds = true
format = "[$duration](bright-black)"

[directory]
truncation_length = 3
truncate_to_repo = true
read_only = " 🔒"
